### ISSUE TITLE
lower limit for the CPU?

### ISSUE THREAD

**Issue by variablo87** [gramps-project/Gramps.js#105]
Is there a lower limit for the CPU? I try to run the docker image at a raspberry PI 3B+, with the [docker-compose.yml](https://raw.githubusercontent.com/gramps-project/web/main/examples/docker-compose-base/docker-compose.yml
). The result was a overload of the CPU. The server wasn't responding. Using Docker is new for me, so what I do wrong?
`docker stats` show:
```
CONTAINER ID   NAME                 CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
c23f9e8b6e18   gramps-grampsweb-1   394.36%   267.8MiB / 909.6MiB   29.45%    6.76kB / 1.68kB   23.3MB / 49.2kB   10
```

```
 $ docker compose up
[+] Running 1/1
 ⠿ Container gramps-grampsweb-1  Created                                                        9.0s
Attaching to gramps-grampsweb-1
gramps-grampsweb-1  | INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
gramps-grampsweb-1  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
gramps-grampsweb-1  | [2022-09-19 13:50:42 +0000] [11] [INFO] Starting gunicorn 20.1.0
gramps-grampsweb-1  | [2022-09-19 13:50:42 +0000] [11] [INFO] Listening at: http://0.0.0.0:5000 (11)
gramps-grampsweb-1  | [2022-09-19 13:50:42 +0000] [11] [INFO] Using worker: sync
gramps-grampsweb-1  | [2022-09-19 13:50:42 +0000] [12] [INFO] Booting worker with pid: 12
gramps-grampsweb-1  | [2022-09-19 13:50:42 +0000] [13] [INFO] Booting worker with pid: 13
gramps-grampsweb-1  | [2022-09-19 13:50:42 +0000] [14] [INFO] Booting worker with pid: 14
gramps-grampsweb-1  | [2022-09-19 13:50:42 +0000] [15] [INFO] Booting worker with pid: 15
gramps-grampsweb-1  | [2022-09-19 13:50:42 +0000] [16] [INFO] Booting worker with pid: 16
gramps-grampsweb-1  | [2022-09-19 13:50:42 +0000] [17] [INFO] Booting worker with pid: 17
gramps-grampsweb-1  | [2022-09-19 13:50:42 +0000] [18] [INFO] Booting worker with pid: 18
gramps-grampsweb-1  | [2022-09-19 13:50:42 +0000] [19] [INFO] Booting worker with pid: 19
```
At my Net-Book it works great.
Intel(R) Celeron(R) 2955U @ 1.40GHz
```
CONTAINER ID   NAME                 CPU %     MEM USAGE / LIMIT     MEM %     NET I/O       BLOCK I/O        PIDS
62cac0e092b2   gramps-grampsweb-1   0.03%     705.2MiB / 1.765GiB   39.01%    12.3kB / 0B   262MB / 65.5kB   10
```

**Comment by DavidMStraub** [comment]
Hi, I am running the hardly modified compose on a Pi 4B. I just checked docker stats; for idle, I also get around 0.04%, when I hit F5 in my browser I see the CPU usage going to 400% for a couple (5-10) of seconds. I am currently using 4 gunicorn workers. This is mostly a memory consideration - in my experience each worker blocks around 100 MB of memory. The current Gramps Web API docker image defaults to 8 but it can be modified with the `GUNICORN_NUM_WORKERS` environment variable.

If you are worried about having too much CPU usage you could reduce the number of workers to 2 or 3.

By the way, 0.15.0 and 0.15.1 released yesterday have an issue that almost all API calls are made twice on app startup. This could be related to the issue you're seeing and should be fixed by the commit I just pushed. So before trying anything else, please try pulling the `latest-devel` image in 5 minutes when the workflow is done...

**Comment by variablo87** [comment]
Thanks for the tip.  I was setup 3 workers.  My raspberry pi 3b+ is now running at 0.03% cpu and 50.83% memory. Maybe this info should be included in the documentation. Thanks for support!

**Comment by GildasLepennetier** [comment]
Hi there! I am so glad I found this threat, since I have exactly the same problem. The dockerized app is eating a 1 Go RAM + swap full and freezing.
How can I actually use the env variable "GUNICORN_NUM_WORKERS" when using docker-compose? I know how to set it up in the terminal, but will that then be "understood" as option when using the command docker-compose up?

**Comment by DavidMStraub** [comment]
I would be grateful for pull requests to improve the documentation. Very limited time this month.

In docker-compose, environment variables are specified under the `environment` key. You can see an example in the [compose file from the documentation](https://raw.githubusercontent.com/gramps-project/web/main/examples/docker-compose-base/docker-compose.yml).

**Comment by DavidMStraub** [comment]
> Edit: I search a bit, and it seem that the answer is there: https://docs.docker.com/compose/environment-variables/

You can use an env file as well, but doing it directly in the YAML is simpler IMO.

**Comment by DavidMStraub** [comment]
Thanks for adding the documentation, I believe this can be closed.
