### ISSUE TITLE
Add import option

### ISSUE THREAD

**Issue by wrmack** [gramps-project/Gramps.js#116]
Say you use the web interface such that your source of truth is the family tree you maintain in your desktop app and you have uploaded it to the web for family to view.  Unless I have missed something, there is no way to re-upload the family tree once you have made changes to it on your desktop app, unless you blow away all images and volumes and start from scratch.  This means everyone has to be set up again as users.  

Once the sync function is available this option won't be so necessary, however it would still be good to have an import option if wanting to change the family tree to a different family tree.

**Comment by DavidMStraub** [comment]
Ok, so there are several issues to distinguish here:

- Exposing the import option (which already exists [in Web API](https://gramps-project.github.io/gramps-webapi/#/importers/postImportFile)) in the UI. This is fairly simple, but it would serve a different purpose from the one you describe. It would be an option to import *additional data*, just as when using the Gramps CLI with the `--import` option. The reason I was hesitant to do that so far is because currently we don't have an option in the API to 1) show the objects to be imported before executing the import or 2) undoing the import. As a user, I would expect one of these two options to be present.
- Replacing the entire tree with a new import. This is currently not possible in Web API. Honestly I also don't see the rationale for implementing it. It would be much cleaner to discard the database with a command on the server.
- Updating the database when changes are made in the Desktop app. This is exactly the case for the [Sync plugin](https://gramps-project.github.io/web/user-guide/sync/). 

So I don't think it would be a good idea to add a "replace tree with import" option to the API or frontend, but I do think it will be useful to have an import option in the frontend.

**Comment by wrmack** [comment]
Makes sense.  Thanks for your work on this.

**Comment by DavidMStraub** [comment]
> The reason I was hesitant to do that so far is because currently we don't have an option in the API to 1) show the objects to be imported before executing the import or 2) undoing the import. As a user, I would expect one of these two options to be present.

I changed my mind about this and implemented simple import in #223.

The reason for my change of heart is that actually Gramps Desktop also doesn't allow previewing or undoing an import, and implementing it would require significant backend work. So it seems overly ambitious to make this a prerequisite for this feature. Several users gave feedback that it was possible to import a tree in the first run assistant, but not afterwards.
