### ISSUE TITLE
Delete Objects

### ISSUE THREAD

**Issue by genofire** [gramps-project/Gramps.js#119]
It would be nice to delete Media Object.
if you upload the wrong image / scan (e.g. in bad quality).

**Comment by DavidMStraub** [comment]
Yes, it's true for all object types. Deleting would be simple to implement in principle, but I've shied away from it so far, as long as it's not easily possible to undo. I would like to wait for something like https://github.com/gramps-project/gramps-webapi/issues/320 to be available in the backend before adding this button...

**Comment by StephenAdams-hamont** [comment]
Indeed a soft delete option would be very welcome. There's always the odd family member who decides to delete things they'd rather hide/forget.

**Comment by fuelen** [comment]
IMO, soft deletion is not necessary and can be added later if really needed. This is not present in desktop version (as I use it, I didn't notice), and I don't expect it here as well.

**Comment by StephenAdams-hamont** [comment]
Multi-user access is not really available in the desktop version either, it
is the sharing of the database and allowing others into it that makes it a
more realistic use case vs the solo user.

**Comment by DavidMStraub** [comment]
I would distinguish two things here: 1) temporary undo, which is useful for reverting an accidental deletion and 2) persistent change history (aka versioning).

1) is also present in the Desktop version. It keeps an undo history in memory until the app is closed. 1) is what I'm mostly thinking about here - for instance a toast notification allowing the user to undo the delete for 20 seconds or so, as in many other web apps. Of course, this does not protect against vandalism. But this is anyway something that is hard to prevent if there is a malicious user with too many permissions. 

2) was discussed a bit [here](https://github.com/gramps-project/gramps-webapi/issues/320). It would be great, but not strictly necessary for the delete option IMO.

**Comment by alcaprar** [comment]
I just realized there is no delete button and I agree that would be very useful but should also be done carefully.
What if you could add this feature behind a config/feature flag that is disabled by default?
In my case I'm the only user and I'd mine enabling it since there is no risk of vandalism.

**Comment by DavidMStraub** [comment]
I think a feature flag is not needed because that's handled by the permission system. You can make all other users "Guests" and they will not be able to edit. You can also make some users "Contributors" and they will be able to add objects, but not edit or delete. What is not possible is to allow users to edit but not delete, but this anyway wouldn't make sense in my opinion as you can always edit something to an empty state.

By the way, this permission system is important already now because even if we don't expose the delete function in the frontend, a user with sufficient permissions can send a `DELETE` request to the API manually.

**Comment by PovilasID** [comment]
I think it is nice to aspire to make actions reversable, however people hosting gramps-web are not desktop users. People who administer servers will have independent backup solutions made for their servers. 
Because of it I disagree with the need to wait for undo button on top of that the referenced issue. With delete and basic merging the desktop client could be almost completely removed from the process. I think simplifying the experience should be the priority.

**Comment by DavidMStraub** [comment]
It's not either/or; undo was added in Web API [v1.0.0](https://github.com/gramps-project/gramps-webapi/releases/tag/v1.0.0) last month, so it's simple to implement soft delete now - just with a snackbar saying "Person deleted. UNDO"

**Comment by kerbless** [comment]
+1 for this, much needed!

The only way to delete a person now is to use the sync plugin

**Comment by DavidMStraub** [comment]
Please refrain from making "+1" comments. There has been enough discussion on this issue.

**Comment by albert-a** [comment]
I've just added a Family just to test, but found out that I can't delete it. That's really unexpected. Now I need to delete all data and recreate it.
