### ISSUE TITLE
Show Event Description Field for Event References

### ISSUE THREAD

**Issue by brucejackson** [gramps-project/Gramps.js#23]
**Issue**
When Gramps.js displays Event references the description shows the Event Type and Date.   This makes it hard to understand to whom the event relates.

**Enhancement**
I think it would be preferable to display the Description field from the API, if it has a value:  For example:  
Event Type - Description - Date
Birth - Birth of Jackson, Dorothy Bessie - 1899-11-12  

If the field is null, the display:  Event Type - Principal Name - Date (if this is too much load because of extra API calls that probably leave as is).

![image](https://user-images.githubusercontent.com/1219029/125801424-6b1275c7-5f3a-4656-bdb7-d462db079a16.png)

**Api result for first birth event**
`{"attribute_list": [], "change": 1612226646, "citation_list": ["e8d8b189339242de211646a8011"], "date": {"calendar": 0, "dateval": [12, 11, 1899, false], "format": null, "modifier": 0, "newyear": 0, "quality": 0, "sortval": 2414971, "text": "12 Nov 1899", "year": 1899}, "description": "Birth of Jackson, Dorothy Bessie", "gramps_id": "E0007", "handle": "e530e29bb601a88149f5b58bef5", "media_list": [{"attribute_list": [], "citation_list": [], "note_list": [], "private": false, "rect": [], "ref": "ea9c1ee5cc51dadcbb222a3d83b"}], "note_list": [], "place": "e530e29f70828efab3e020d11c2", "private": false, "tag_list": [], "type": "Birth"}`

**Comment by DavidMStraub** [comment]
I agree this is a problem, but using the description is only a solution if you have the name of the person in the description field - I personally never do that (because I find it redundant).

The solution, as you write, would be to look for the primary participant - but this would involve another API call (actually, one for each reference entry - this is fine for a single person with two or three references, but think e.g. of a place which can have hundreds of references!).

So I'm not sure what would be a good way to do it right now.

**Comment by brucejackson** [comment]
I understand both points here.  I adopted the practice of entering the description based on the screenshots from Gramps website and images in the wiki.   I agree that is it redundant and extra typing but I have found them helpful.

On the extra API calls, would sorting and pagination of the results be helpful?   It would help show different types of objects that are referenced and each screen would have fewer API calls.  A big question is would look too cumbersome and confusing?    

I hope this crude table of the reference page helps illustrate.  

| Sample Layout |  |  | |
|-------------------------|------------|---------------------|------|
| (Existing Set of Tabs)              | Map        | **References**      |      |
| (New Set of Sub Tab)               | **Events** | Places              |      |
| (Listing of 20 results) | Event Type | Primary Participant | Date |
| (Pagination Control)    |            | << 1   2  3  >>     |      |

**Comment by brucejackson** [comment]
Hi David,

I've been poking through this issue.  It looks like the code Event Description in the References tabs is coming from here the eventTitleFromProfile function.
https://github.com/DavidMStraub/Gramps.js/blob/a6e0aa02f2f960c22e559fd5322a93b0e2d0c4f2/src/util.js#L40

To alleviate concerns over the # of API calls, maybe a limit on the number of Primary People that are displayed (e.g. 2 people) and then concatenate those to names with the # of other Individuals and Families that are not displayed.  Something like,

| Type  | Description                                                                         |
|-------|-------------------------------------------------------------------------------------|
| Event | Party - Jackson, Bruce; Straub, David; plus 2 Individuals and 2 Families (2021-08-12) |
| ...   |                                                                                     |

**Comment by DavidMStraub** [comment]
Actually I'm not even sure what would be the best way to query all the events referring to a particular place in the API at the moment.

So I think the best solution would be to add the generated title ("Birth of Jackson, Dorothy Bessie") as part of the event profile in the backend. This would make the `eventTitleFromProfile` function in the frontend obsolete.

**Comment by DavidMStraub** [comment]
Note to self: the following references exist for given object types

### Can refer to multiple object types

- Citation: Person, Family, Event, Place, Media, Repository
- Media: Person, Family, Event, Place, Source, Citation
- Note: Person, Family, Event, Place, Media, Source, Citation, Repository
- Place: Event, Place (would make sense to split into events and "encloses" tabs)

### Refs with unique object types:

- Repository: Source. This should be replaced by a proper sources tab
- Source: Citation. This should be replaced by a proper citation tab

### Not used in Gramps.js:

- Person: Family, Person; not shown in Gramps.js since duplicates relationships/association tabs
- Family: Person; not shown in Gramps.js since duplicates children tab
- Event: Family, Person; not shown in Gramps.js since duplicates participant tab
- Tag: All except tag; not shown in Gramps.js since we don't have a tag view

**Comment by DavidMStraub** [comment]
I realized this was fixed and this issue never closed. Don't even remember when exactly, probably in [v0.17](https://github.com/gramps-project/Gramps.js/releases/tag/v0.17.0).
