### ISSUE TITLE
Grampsweb image on Docker Hub 

### ISSUE THREAD

**Issue by terual** [gramps-project/Gramps.js#250]
As a Synology user I cannot use the ghcr registry when I am using the Synology Docker frontend. The dmstraub/gramps-webapi image on Docker Hub is updated regularly (I believe it is also the base for the ghcr.io/gramps-project/grampsweb). But the dmstraub/grampsweb image has not been updated in 2 years. Would it be possible to also publish the dockerweb images to Docker Hub?

**Comment by DavidMStraub** [comment]
Hi, the ghcr.io are much more convenient for us since they are well integrated into the Github actions workflow, which is what we use to build the images. Moreover, it makes more sense from a permissions perspective, as the Dockerhub dmstraub/... images are under my personal namespace, not the Gramps community's. Can you elaborate why Synology does not allow other registries? Given the recent changes on Dockerhub trying to restrict and limit free repositories, I think it's more likely the remaining images will move to Github as well.

**Comment by terual** [comment]
Someone on Stackoverflow reached out to Synology support and this was their answer:

> 2022-10-27 - Synology Support replied and the official statement is that the token authentication currently used by Github Container Registry is not supported on the DSM's Docker package GUI. Its possible to ssh to the DSM and use docker from the command line.

(https://stackoverflow.com/questions/73825556/adding-ghcr-github-docker-regustry-to-synology-docker-results-in-registry-ret)

**Comment by DavidMStraub** [comment]
But for pulling a public package, no token is needed, so this answer doesn't really apply :thinking:

**Comment by terual** [comment]
To pull an image from the GUI you first need to add the registry, and for that you need a token apperently.

So I looked a bit further and I tried to pull via the command line and that seemed to work!

For future reference:
1. SSH into the NAS using admin credentials 
2. Execute as root:
`# docker pull ghcr.io/gramps-project/grampsweb:latest`
3. The image appears in the GUI under the Image tab.
