### ISSUE TITLE
Clarify code formatting for development

### ISSUE THREAD

**Issue by DavidMStraub** [gramps-project/Gramps.js#86]
See #85.

**Comment by DavidMStraub** [comment]
@khashashin, stupid question, when you have set up the new development environment and did `npm install`, did you also get a git pre-commit hook installed which checks for formatting? I just realized this (after reinstalling) and I guess it comes from [this](https://github.com/gramps-project/Gramps.js/blob/main/package.json#L54-L65) but for some reason that didn't have an effect on me previously. Possibly it's because I've updated Node.js.

**Comment by khashashin** [comment]
> @khashashin, stupid question, when you have set up the new development environment and did `npm install`, did you also get a git pre-commit hook installed which checks for formatting?

Yes.

pre-commit was installed and also the linting checks were triggered correctly. I could not commit my changes due to linting issues so the result of this was my PR https://github.com/gramps-project/Gramps.js/pull/85 :)

Since there were a lot of linting issues, I just disabled pre-commit so I could push my changes.

I was planning on writing e2e tests before fixing the linting issues so we don't unconsciously break anything.
